# Generated by Django 4.1.2 on 2022-11-06 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.SmallAutoField(primary_key=True, serialize=False)),
                ('name_category', models.CharField(max_length=20)),
                ('type_category', models.CharField(choices=[('01', 'Hortalizas'), ('02', 'Hierbas aromáticas'), ('03', 'Especias')], default='01', max_length=2)),
            ],
        ),
    ]
