# Generated by Django 4.1.2 on 2022-11-06 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='type_category',
            field=models.SmallIntegerField(max_length=2),
        ),
    ]
