# Generated by Django 4.1.2 on 2022-11-07 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_alter_category_type_category'),
        ('crop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='id_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
    ]
