# Generated by Django 4.1.3 on 2022-11-11 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crop', '0002_alter_crop_id_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crop',
            options={'ordering': ['name_crop']},
        ),
        migrations.AlterField(
            model_name='crop',
            name='distance_crops',
            field=models.PositiveSmallIntegerField(default=40),
        ),
        migrations.AlterField(
            model_name='crop',
            name='height_max_crop',
            field=models.PositiveSmallIntegerField(default=4),
        ),
        migrations.AlterField(
            model_name='crop',
            name='name_crop',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='crop',
            name='time_germination',
            field=models.PositiveSmallIntegerField(default=10),
        ),
    ]
