# Generated by Django 4.1.3 on 2022-11-17 21:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0003_alter_category_type_category'),
        ('crop', '0003_alter_crop_options_alter_crop_distance_crops_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crop',
            name='id_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.category'),
        ),
        migrations.AlterField(
            model_name='crop',
            name='id_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
