# Generated by Django 4.1.3 on 2022-12-02 17:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('category', '0003_alter_category_type_category'),
        ('crop', '0004_alter_crop_id_category_alter_crop_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='id_category',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='id_user',
        ),
        migrations.CreateModel(
            name='Crop2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('id_user', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
