# Generated by Django 4.1.2 on 2022-11-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name_user', models.CharField(max_length=30)),
                ('lastname_user', models.CharField(max_length=30)),
                ('email_user', models.EmailField(max_length=50)),
                ('password_user', models.CharField(max_length=30)),
            ],
        ),
    ]
